# Generated by Django 6.0.3 on 2026-04-01 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('doc_type', models.CharField(choices=[('Ordinance', 'Ordinance'), ('Resolution', 'Resolution')], max_length=50)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Archived', 'Archived')], default='Pending', max_length=50)),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Upload', 'Upload'), ('Edit', 'Edit'), ('Delete', 'Delete'), ('View', 'View')], max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.legislativedocument')),
            ],
        ),
    ]
