# Generated by Django 6.0.3 on 2026-04-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativedocument',
            name='date_enacted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legislativedocument',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legislativedocument',
            name='physical_storage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legislativedocument',
            name='sponsor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legislativedocument',
            name='visibility',
            field=models.CharField(choices=[('Public Access', 'Public Access'), ('Internal Only', 'Internal Only')], default='Public Access', max_length=50),
        ),
    ]
