# Generated by Django 6.0.3 on 2026-04-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_legislativedocument_date_enacted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativedocument',
            name='co_sponsors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
