# Generated by Django 6.0.3 on 2026-04-24 18:48

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_legislativedocument_co_sponsors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislativedocument',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=core.models.document_upload_path),
        ),
        migrations.CreateModel(
            name='ArchivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_id', models.CharField(max_length=100, unique=True)),
                ('original_document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('Ordinance', 'Ordinance'), ('Resolution', 'Resolution')], max_length=50)),
                ('year', models.IntegerField()),
                ('date_enacted', models.DateField(blank=True, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('co_sponsors', models.CharField(blank=True, max_length=500, null=True)),
                ('visibility', models.CharField(choices=[('Public Access', 'Public Access'), ('Internal Only', 'Internal Only')], default='Internal Only', max_length=50)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_storage', models.CharField(blank=True, max_length=255, null=True)),
                ('retention_policy', models.CharField(choices=[('Permanent', 'Permanent'), ('10 Years', '10 Years'), ('5 Years', '5 Years'), ('Pending Disposal', 'Pending Disposal')], default='Permanent', max_length=50)),
                ('original_date_filed', models.DateField(blank=True, null=True)),
                ('date_archived', models.DateField(auto_now_add=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to=core.models.archive_upload_path)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
