# Generated by Django 6.0.4 on 2026-04-25 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_legislativedocument_file_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislativedocument',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('1st reading', '1st reading'), ('2nd reading', '2nd reading'), ('3rd reading', '3rd reading'), ('For Certification', 'For Certification'), ('For Signing', 'For Signing'), ('For Approval', 'For Approval'), ('Vetoed', 'Vetoed')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ArchiveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='archiveddocument',
            name='custom_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.archivefolder'),
        ),
    ]
