# Generated by Django 6.0.3 on 2026-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_legislativedocument_status_archivefolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativedocument',
            name='veto_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
