# Generated by Django 6.0.3 on 2026-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_legislativedocument_veto_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddocument',
            name='veto_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
