# Generated by Django 6.0.3 on 2026-05-14 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auditlog_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetoedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('Ordinance', 'Ordinance'), ('Resolution', 'Resolution')], max_length=50)),
                ('year', models.IntegerField()),
                ('date_enacted', models.DateField(blank=True, null=True)),
                ('sponsor', models.CharField(blank=True, max_length=255, null=True)),
                ('co_sponsors', models.CharField(blank=True, max_length=500, null=True)),
                ('visibility', models.CharField(choices=[('Public Access', 'Public Access'), ('Internal Only', 'Internal Only')], default='Public Access', max_length=50)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_storage', models.CharField(blank=True, max_length=255, null=True)),
                ('veto_reason', models.TextField(blank=True, null=True)),
                ('date_filed', models.DateField(blank=True, null=True)),
                ('date_vetoed', models.DateField(auto_now_add=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='vetoed/')),
                ('vetoed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetoed_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
