# Generated by Django 6.0.4 on 2026-05-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backuplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Upload', 'Upload'), ('Edit', 'Edit'), ('Delete', 'Delete')], max_length=50),
        ),
    ]
