# Generated by Django 6.0.4 on 2026-05-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='backup_type',
            field=models.CharField(choices=[('auto', 'Automatic (Login)'), ('manual', 'Manual'), ('restore', 'Restore')], max_length=20),
        ),
    ]
