# Generated by Django 6.0.4 on 2026-05-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_backuplog_backup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='users_synced',
            field=models.IntegerField(default=0),
        ),
    ]
