# Generated by Django 6.0.4 on 2026-06-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_backuplog_users_synced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('Upload', 'Upload'), ('Edit', 'Edit'), ('Delete', 'Delete'), ('Generate Report', 'Generate Report'), ('Share', 'Share')], max_length=50),
        ),
    ]
