# Generated by Django 6.0.4 on 2026-06-20 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('1st reading', '1st reading'), ('2nd reading', '2nd reading'), ('3rd reading', '3rd reading'), ('For Certification', 'For Certification'), ('For Signing', 'For Signing'), ('For Approval', 'For Approval'), ('Vetoed', 'Vetoed')], max_length=50)),
                ('update_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='progress_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_updates', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='core.legislativedocument')),
            ],
            options={
                'db_table': 'document_progress',
                'ordering': ['-update_date'],
            },
        ),
    ]
