# Generated by Django 6.0.4 on 2026-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_archiveddocument_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveddocument',
            name='doc_type',
            field=models.CharField(choices=[('Ordinance', 'Ordinance'), ('Resolution', 'Resolution')], max_length=50),
        ),
        migrations.AlterField(
            model_name='legislativedocument',
            name='doc_type',
            field=models.CharField(choices=[('Ordinance', 'Ordinance'), ('Resolution', 'Resolution')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vetoeddocument',
            name='doc_type',
            field=models.CharField(choices=[('Ordinance', 'Ordinance'), ('Resolution', 'Resolution')], max_length=50),
        ),
    ]
