# Generated by Django 6.0.4 on 2026-06-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_archiveddocumentprogress_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislativedocument',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vetoeddocument',
            name='title',
            field=models.TextField(),
        ),
    ]
