# Generated by Django 6.0.4 on 2026-06-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_legislativedocument_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveddocument',
            name='title',
            field=models.TextField(),
        ),
    ]
