# Generated by Django 6.0.4 on 2026-06-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_archiveddocument_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='documents_group', max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pending_broadcasts',
                'ordering': ['created_at'],
            },
        ),
    ]
