# Generated by Django 6.0.4 on 2026-06-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_pendingbroadcast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={},
        ),
        migrations.AlterField(
            model_name='archiveddocumentprogress',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Urgent', 'Urgent'), ('Archived', 'Archived'), ('Proposed Measures', 'Proposed Measures'), ('Endorsement', 'Endorsement'), ('Referral', 'Referral'), ('Committee Meetings', 'Committee Meetings'), ('Committee Report', 'Committee Report'), ('1st reading', '1st reading'), ('2nd reading', '2nd reading'), ('3rd reading', '3rd reading'), ('For Certification', 'For Certification'), ('For Signing', 'For Signing'), ('For Approval', 'For Approval'), ('Vetoed', 'Vetoed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentprogress',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Urgent', 'Urgent'), ('Archived', 'Archived'), ('Proposed Measures', 'Proposed Measures'), ('Endorsement', 'Endorsement'), ('Referral', 'Referral'), ('Committee Meetings', 'Committee Meetings'), ('Committee Report', 'Committee Report'), ('1st reading', '1st reading'), ('2nd reading', '2nd reading'), ('3rd reading', '3rd reading'), ('For Certification', 'For Certification'), ('For Signing', 'For Signing'), ('For Approval', 'For Approval'), ('Vetoed', 'Vetoed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='legislativedocument',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Urgent', 'Urgent'), ('Archived', 'Archived'), ('Proposed Measures', 'Proposed Measures'), ('Endorsement', 'Endorsement'), ('Referral', 'Referral'), ('Committee Meetings', 'Committee Meetings'), ('Committee Report', 'Committee Report'), ('1st reading', '1st reading'), ('2nd reading', '2nd reading'), ('3rd reading', '3rd reading'), ('For Certification', 'For Certification'), ('For Signing', 'For Signing'), ('For Approval', 'For Approval'), ('Vetoed', 'Vetoed')], db_index=True, default='Pending', max_length=50),
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table=None,
        ),
    ]
