# Generated by Django 6.0.4 on 2026-06-29 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='support_tickets',
        ),
    ]
