"""
Django settings for legishub project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'
if not DEBUG and not SECRET_KEY:
    raise ValueError("The SECRET_KEY environment variable must be set in production.")

# Safely parse Allowed Hosts
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '*')
if allowed_hosts_env.startswith('[') and allowed_hosts_env.endswith(']'):
    import json
    try:
        ALLOWED_HOSTS = json.loads(allowed_hosts_env.replace("'", '"'))
    except Exception:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]

# Automatically allow local IPs during development
if DEBUG:
    ALLOWED_HOSTS.extend(['192.168.1.34', 'localhost', '127.0.0.1', '172.20.10.1', '*'])

# Automatically allow the Render deployment URL
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Automatically allow the Railway deployment URL
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'django_q',
    'anymail',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.MaintenanceModeMiddleware',  # ADDED MAINTENANCE MODE MIDDLEWARE
]

ROOT_URLCONF = 'legishub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'legishub.wsgi.application'
ASGI_APPLICATION = 'legishub.asgi.application'

# WebSocket Channel Layer (Use Redis in Production)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Fallback to Railway's default PG variables if DB_NAME isn't set
DB_NAME = os.getenv('DB_NAME') or os.getenv('PGDATABASE')

if DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': os.getenv('DB_USER') or os.getenv('PGUSER'),
            'PASSWORD': os.getenv('DB_PASSWORD') or os.getenv('PGPASSWORD'),
            'HOST': os.getenv('DB_HOST') or os.getenv('PGHOST'),
            'PORT': os.getenv('DB_PORT') or os.getenv('PGPORT', '5432'),
            'OPTIONS': {
                'sslmode': os.getenv('DB_SSL_MODE') or ('require' if not DEBUG else 'prefer'),
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ==========================================
# CACHE CONFIGURATION (DATABASE CACHE)
# ==========================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'legishub_cache',
    }
}


# Password validations
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'core.validators.ComplexPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ==========================================
# PRODUCTION SECURITY SETTINGS
# ==========================================
if not DEBUG:
    # Tells Django it is running behind a secure proxy (Render) so CSRF cookies work
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # REQUIRED FOR DJANGO 4.0+ OVER HTTPS TO ALLOW LOGINS/POST REQUESTS
    CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host not in ['localhost', '127.0.0.1']]

# ==========================================
# FILE STORAGE (SUPABASE S3 COMPATIBLE)
# ==========================================
USE_S3 = os.getenv('USE_S3', 'False') == 'True'

if USE_S3:
    # Use Supabase Storage via django-storages (boto3)
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"}, 
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"}
    }
    AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('SUPABASE_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('SUPABASE_BUCKET_NAME', 'legishub-media')
    AWS_S3_ENDPOINT_URL = os.getenv('SUPABASE_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = os.getenv('SUPABASE_REGION_NAME', 'ap-southeast-1')
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_S3_FILE_OVERWRITE = False
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"}
    }

# ==========================================
# IFRAME SECURITY (ALLOW PDF PREVIEWS)
# ==========================================
X_FRAME_OPTIONS = 'SAMEORIGIN'

# ==========================================
# EMAIL CONFIGURATION (BREVO / SENDINBLUE API)
# ==========================================
# Dynamic backend configuration to support both older and newer django-anymail versions
try:
    from anymail.backends.brevo import EmailBackend
    EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
    ANYMAIL = {
        'BREVO_API_KEY': os.getenv('BREVO_API_KEY') or os.getenv('SENDINBLUE_API_KEY'),
    }
except ImportError:
    EMAIL_BACKEND = 'anymail.backends.sendinblue.EmailBackend'
    ANYMAIL = {
        'SENDINBLUE_API_KEY': os.getenv('SENDINBLUE_API_KEY') or os.getenv('BREVO_API_KEY'),
    }

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Marikina LegisHub <noreply@legishub-marikina.me>')
if DEFAULT_FROM_EMAIL:
    DEFAULT_FROM_EMAIL = DEFAULT_FROM_EMAIL.strip("'\"")

# ==========================================
# LOGIN REDIRECT URL
# ==========================================
# Tells @login_required to redirect here instead of the default /accounts/login/
LOGIN_URL = 'login'

# ==========================================
# DJANGO Q2 BACKGROUND TASK SETTINGS
# ==========================================
Q_CLUSTER = {
    'name': 'legishub_cluster',
    'workers': 1,           # Reduced to 1 for Render Free Tier RAM limits
    'recycle': 500,         # Restarts workers to prevent memory leaks
    'timeout': 300,         # Max seconds a task is allowed to run
    'retry': 360,           # Must be greater than timeout so slow tasks aren't duplicated
    'compress': True,       # Compresses database logs to save space
    'save_limit': 250,      # Keeps the last 250 task logs in the database
    'queue_limit': 500,
    # 'cpu_affinity': 1,    # <--- REMOVE/COMMENT THIS OUT ON WINDOWS!
    'label': 'Django Q2',   # Name it will show in the Django Admin
    'orm': 'default',       # <--- CRITICAL: Tells it to use your PostgreSQL DB!
    'sync': os.getenv('DJANGO_Q_SYNC', 'False') == 'True'
}